# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build

on:
  push:
    branches: [ "main","add-chia-tests-git-workflow" ]
  pull_request:
    branches: [ "main","add-chia-tests-git-workflow"]

  build:

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chia-network/chia:latest
      env:
        testnet: true
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
      ports:
      - 8444
      
    steps:
    - name: Initialize Chia
      run: chia init
    - name: Import Test Wallet Using Seed
      run: chia keys add ${{ build.WALLET_KEY }}
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      

    - name: Test
      run: dotnet test --no-build --verbosity normal
