# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build

on:
  workflow_dispatch:
  push:
    branches: [ "main","add-chia-tests-git-workflow" ]
  pull_request:
    branches: [ "main","add-chia-tests-git-workflow"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chia-network/chia:latest
      env:
        testnet: true
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1,
      ports:
      - 8444:8444
      
    steps:  
    - name: install icu components
      run: sudo apt-get update && sudo apt-get install -y sudo apt-transport-https && apt-cache search icu
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      

    - name: Test
      run: dotnet test --no-build --verbosity normal
